### ISSUE TITLE
cargo test not working for library

### ISSUE THREAD

**Issue by incker2** [duncandean/luno-rust#7]
cargo test not working for library

    error[E0277]: `main` has invalid return type `impl std::future::Future`
    --> examples\get-pending-transactions.rs:4:17
    |
    4 | async fn main() {
        |                 ^ `main` can only return types that implement `std::process::Termination`
        |
        = help: consider using `()`, or a `Result`

**Comment by dunxen** [comment]
Thanks, will be spending some more time on this soon.
